### ISSUE TITLE
Share button Icons order change

### ISSUE THREAD

**Issue by vasu592** [MurhafSousli/ng2-sharebuttons#105]
Hello 
I want to change image positions.
i.e, facebook, twitter, linkedIn, google+
i want this order, please tell me how can i change .

**Comment by MurhafSousli** [comment]
Hi @vasu592 in your global style `style.scss`
```css
.sb-buttons {
  .facebook{
     order: 1;
  }
  .twitter{
     order: 2;
  }
  .linkedin{
     order: 3;
  }
  .googleplus{
     order: 4;
  }
}
```
